<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:context="http://www.springframework.org/schema/context"
           xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.springframework.org/schema/context
           http://www.springframework.org/schema/context/spring-context.xsd
           http://www.springframework.org/schema/mvc
           http://www.springframework.org/schema/mvc/spring-mvc.xsd
">

    <context:component-scan base-package="com.lutton.controller"/>
    <mvc:annotation-driven/>

<!--    异常处理方式一：-->
<!--    <bean class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver">-->
<!--        <property name="defaultErrorView" value="defaultErrorView.jsp"/>-->
<!--        <property name="exceptionMappings">-->
<!--            <map>-->
<!--                <entry key="java.lang.ArithmeticException" value="ArithmeticException.jsp"/>-->
<!--                <entry key="java.lang.NullPointerException" value="NullPointerException.jsp"/>-->
<!--                <entry key="com.lutton.exceprion.MyException" value="MyException.jsp"/>-->
<!--            </map>-->
<!--        </property>-->
<!--    </bean>-->
    <bean class="com.lutton.resolver.MyExceptionResolver"/>

</beans>